// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA7PYPKZBLbcC0b3hJAx3jVh45cTyTwlY',
    appId: '1:901859231566:web:313b2e750798857a29401f',
    messagingSenderId: '901859231566',
    projectId: 'flutterdemoapp-cc350',
    authDomain: 'flutterdemoapp-cc350.firebaseapp.com',
    storageBucket: 'flutterdemoapp-cc350.appspot.com',
    measurementId: 'G-7LBFSZRYVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXM3bVHUdY148vQDGemFOp2oSsVTm6ozA',
    appId: '1:901859231566:android:8db5294de070305229401f',
    messagingSenderId: '901859231566',
    projectId: 'flutterdemoapp-cc350',
    storageBucket: 'flutterdemoapp-cc350.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBebfIsBCSdrBLWysSWOqbKIu5zV69HzU4',
    appId: '1:901859231566:ios:b4f4aed9b47fedc529401f',
    messagingSenderId: '901859231566',
    projectId: 'flutterdemoapp-cc350',
    storageBucket: 'flutterdemoapp-cc350.appspot.com',
    iosClientId: '901859231566-27v17eihgp063k10nr6tfhmu67cnhfrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBebfIsBCSdrBLWysSWOqbKIu5zV69HzU4',
    appId: '1:901859231566:ios:481ab75eb5d9480929401f',
    messagingSenderId: '901859231566',
    projectId: 'flutterdemoapp-cc350',
    storageBucket: 'flutterdemoapp-cc350.appspot.com',
    iosClientId: '901859231566-em37p9o9s706ov8vuborvnt2m48h17e7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemoApp.RunnerTests',
  );
}
